### ISSUE TITLE
data_dir "./vector-data" does not exist

### ISSUE THREAD

**Issue by Djiit** [anglinb/heroku-vector-logplex#1]
Hey there 👋 

Trying to play with this, but when I deploy it, I've got this error : 
```
data_dir "./vector-data" does not exist
```

Any idea what I'm missing?

Thanks!

**Comment by anglinb** [comment]
Hey @Djiit! This is a bit confusing, you need to have that directory created in the repo you push to heroku. Check out this example project I created: https://github.com/anglinb/heroku-logplex-vector-example I was able to get it working with a heroku button so just press that and it should work! 🎉

**Comment by Djiit** [comment]
Awesome! I was using the timberio buildpack directly... sounds like yours solve this!
